### ISSUE TITLE
Lupa/Soporte para soldar

### ISSUE THREAD

**Issue by lejouson** [jisbert/zmk-config#5]
No gastarme mucho en esto. La alfombrilla ya es suficiente.

Preferiblemente una lupa, gafas lupa, lupa de relojero o microscopio. Las gafas las puedo usar sin luz quitándoles las pilas para reducir el peso, ya que tengo la lámpara Xiaomi. 

- Grande con rieles y mordazas ajustables con palomillas.
  - [Amazon, 20 €.](https://www.amazon.es/Ajustable-limpiador-soldadura-herramienta-reparaci%C3%B3n/dp/B07PGN4SWM?ref_=Oct_d_obs_d_3052222031&pd_rd_w=AkOpi&pf_rd_p=cdb83d9d-4f9f-410d-8659-f550326a04d5&pf_rd_r=8T1EY18ZDSV1PGD33FP6&pd_rd_r=0673484f-4c10-4c7c-aa0f-75590c863d86&pd_rd_wg=bMux3&pd_rd_i=B07PGN4SWM#customerReviews)
  - [Wallapop, Barcelona, 6 €.](https://es.wallapop.com/item/soporte-universal-ajustable-para-circuitos-u-otros-680424944)
- Magnético con pinzas.
  - [Amazon, 41 €.](https://www.amazon.es/soldadura-herramienta-magn%C3%A9tica-reparaci%C3%B3n-electr%C3%B3nica/dp/B07X1R7QMQ?ref_=Oct_d_otopr_d_3052222031&pd_rd_w=KgPKR&pf_rd_p=cab367fc-20d4-4237-9fdb-3b923bfdd330&pf_rd_r=8T1EY18ZDSV1PGD33FP6&pd_rd_r=0673484f-4c10-4c7c-aa0f-75590c863d86&pd_rd_wg=bMux3&pd_rd_i=B07X1R7QMQ&th=1)
  - [Amazon, lupa y ventilador, 28 €.](https://www.amazon.es/Ajustables-Reparaci%C3%B3n-Herramienta-giratorios-LITEBEE/dp/B07FR2N9N2?ref_=Oct_d_otopr_d_3052222031&pd_rd_w=KgPKR&pf_rd_p=cab367fc-20d4-4237-9fdb-3b923bfdd330&pf_rd_r=8T1EY18ZDSV1PGD33FP6&pd_rd_r=0673484f-4c10-4c7c-aa0f-75590c863d86&pd_rd_wg=bMux3&pd_rd_i=B07233QBBS&th=1)
  - [Amazon, con lupa, linterna y ventilador, 33 €.](https://www.amazon.es/Terceras-Soldadura-Herramientas-Giratoria-Ventilador/dp/B08MPVLR43/ref=sr_1_18?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ZU5FMYAS7YVO&dchild=1&keywords=lupa+soldadura&qid=1632649524&qsid=257-6431409-8940720&s=tools&sprefix=lupa%2Cdiy%2C192&sr=1-18&sres=B07V2XT2MT%2CB099DWRQ8P%2CB000T9UCHI%2CB07W8T4YCR%2CB077YK4GLV%2CB088R32QG6%2CB07K2FR63D%2CB08L6CYR4P%2CB07WF7GXS1%2CB0724ZNNGW%2CB07Z53BRHM%2CB07MZBX63Q%2CB08MPVLR43%2CB07P5Y6PK2%2CB000O3RJFC%2CB001BMSBD4)
  - [Wallapop, Alicante, 14 €, aunque es posible que se lo consiga rebajar.](https://es.wallapop.com/item/soporte-pcb-para-microsoldadura-kaisi-k1208-684639296)
- Lupa básica con pinzas.
  - [Amazon, 17 €.](https://www.amazon.es/Hi-Spec-soldadura-limpieza-electr%C3%B3nica-artesan%C3%ADa/dp/B08H214H3W/ref=lp_3052222031_1_10)
  - [Amazon, 13,33 €](https://www.amazon.es/Rolson-60335-Soporte-para-soldadores/dp/B001BMSBD4/ref=sr_1_21?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ZU5FMYAS7YVO&dchild=1&keywords=lupa%2Bsoldadura&qid=1632649524&qsid=257-6431409-8940720&s=tools&sprefix=lupa%2Cdiy%2C192&sr=1-21&sres=B07V2XT2MT%2CB099DWRQ8P%2CB000T9UCHI%2CB07W8T4YCR%2CB077YK4GLV%2CB088R32QG6%2CB07K2FR63D%2CB08L6CYR4P%2CB07WF7GXS1%2CB0724ZNNGW%2CB07Z53BRHM%2CB07MZBX63Q%2CB08MPVLR43%2CB07P5Y6PK2%2CB000O3RJFC%2CB001BMSBD4&th=1)
- Gafas lupa
  - [Amazon, 1,5x-3,5x, 18 €.](https://www.amazon.es/Lupa-LED-Luces-Reparaciones-Intercambiables/dp/B01GTF06PS/ref=sr_1_49_sspa?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ZU5FMYAS7YVO&dchild=1&keywords=lupa+soldadura&qid=1632651027&s=tools&sprefix=lupa%2Cdiy%2C192&sr=1-49-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzSlYzOFdPNVI3OVhCJmVuY3J5cHRlZElkPUEwMTk4MDU1Mk5LMTZDNzQyMlZRRCZlbmNyeXB0ZWRBZElkPUEwMDIwNzU5S0ZFMFNGT05VWEZOJndpZGdldE5hbWU9c3BfYnRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==#customerReviews)
  - [Amazon, 10x - 25x, 17 €.](https://www.amazon.es/EUROXANTY-Lupa-Gafas-joyero-reparaci%C3%B3n-relojes/dp/B07J2RYQMF/ref=sr_1_16?dchild=1&keywords=gafas+lupa&qid=1633887417&qsid=257-6431409-8940720&sr=8-16&sres=B06XCZYLJL%2CB08881GRHB%2CB07NSBSZV8%2CB08H1LB1VJ%2CB01AL2YAQ6%2CB01GTF06PS%2CB08KT5Z4HL%2CB00KC0RBN2%2CB07MQ5656W%2CB07CH6S6XH%2CB08BJN3V1W%2CB07J2RYQMF%2CB08XX3DK42%2CB07JD1ZJTD%2CB093GXR9B5%2CB085DRKCWZ%2CB018RHYTJK%2CB003H08FHA%2CB075L4PKS6%2CB07WFLNVPH&srpt=MAGNIFIER)
- Microscopio
  - [Amazon, 40x a 1000x, 23 €.](https://www.amazon.es/Microscopio-Digital-Bysameyee-endoscopio-Compatible/dp/B07SR7YPV5/ref=sr_1_7_sspa?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ZU5FMYAS7YVO&dchild=1&keywords=lupa%2Bsoldadura&qid=1632649524&s=tools&sprefix=lupa%2Cdiy%2C192&sr=1-7-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExUkg3SUhRQTQ3V0dCJmVuY3J5cHRlZElkPUEwNTAzNjMwMlo2MlY5SDY0RlNBUSZlbmNyeXB0ZWRBZElkPUEwNzI3OTA5SjJONTI4TUpRMzg5JndpZGdldE5hbWU9c3BfbXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1)

**Comment by jisbert** [comment]
[Microscopio opcional](https://www.amazon.es/Microscopio-Digital-Bysameyee-endoscopio-Compatible/dp/B07SR7YPV5/ref=sr_1_7_sspa?__mk_es_ES=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=ZU5FMYAS7YVO&dchild=1&keywords=lupa%2Bsoldadura&qid=1632649524&s=tools&sprefix=lupa%2Cdiy%2C192&sr=1-7-spons&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUExUkg3SUhRQTQ3V0dCJmVuY3J5cHRlZElkPUEwNTAzNjMwMlo2MlY5SDY0RlNBUSZlbmNyeXB0ZWRBZElkPUEwNzI3OTA5SjJONTI4TUpRMzg5JndpZGdldE5hbWU9c3BfbXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1)

**Comment by jisbert** [comment]
¿Es realmente necesario? Si tengo la alfombrilla no puedo dejar la placa encima?

**Comment by lejouson** [comment]
De momento no he comprado ninguno por no invertir más dinero. Hubiese comprado:

- Gafas lupa de [Digikey](https://www.digikey.es/product-detail/es/aven-tools/26116/243-26116-ND/15278003) o [Amazon](https://www.amazon.es/EUROXANTY-Lupa-Gafas-joyero-reparaci%C3%B3n-relojes/dp/B07J2RYQMF/ref=pd_sbs_3/257-6431409-8940720?pd_rd_w=3vb7L&pf_rd_p=073ad75e-0f2f-4e00-af92-a91d92e1e105&pf_rd_r=6G7V1NMYW02C9ND3X88W&pd_rd_r=a386b73d-2957-4b8b-9f87-9dbb03b1998c&pd_rd_wg=TepE9&pd_rd_i=B07J2RYQMF&psc=1).
- Soporte barato de [Wallapop](https://es.wallapop.com/item/soporte-universal-ajustable-para-circuitos-u-otros-680424944).
