### ISSUE TITLE
Baterías

### ISSUE THREAD

**Issue by lejouson** [jisbert/zmk-config#6]
Con la nice!nano se puede emplear cualquier batería de 3,7 V que tenga [_undervoltage protection_](https://product-help.schneider-electric.com/ED/MTZ/Micrologic_X_User_Guide/EDMS/DOCA0102EN/DOCA0102xx/ProtectionFunctions/ProtectionFunctions-15.htm) ya que la MCU tiene _overcharge protection_.

La recomendada en la [documentación oficial](https://nicekeyboards.com/docs/nice-nano/) y en la página de producto de [splitkb.com](https://splitkb.com/products/nice-nano) es la 301230 porque se puede ubicar ordenadamente debajo de la nice!nano. Aunque para ello, dado que en el Kyria la MCU se monta boca abajo, es necesario emplear unos pines algo más largos que los Millmax que vende splitkb.com.

Documentos:

- [Comparativa de baterías para utilizar con la nice!nano.](https://github.com/joric/nrfmicro/wiki/Batteries)
- [Galería con otras formas de instalar la batería.](https://www.icloud.com/sharedalbum/es-es/#B0XJEsNWnGtVhoq)

Productos:

- [301230, 90 mAh, envío desde el Reino Unido, todo por unos 30 €.](https://www.ebay.es/itm/194001009975)
- [301030, 60 mAh, envío desde España, todo por unos 13 €, en el pasado ha tenido 301230 en stock.](https://www.ebay.es/itm/223866894873?var=522613175589)

**Comment by jisbert** [comment]
https://www.icloud.com/sharedalbum/es-es/#B0XJEsNWnGtVhoq

**Comment by lejouson** [comment]
La nomenclatura utilizada para bautizar las baterías indica su tamaño. De esa forma, la 301228 mide 30 x 12 x 2,28 mm3. Esto quiere decir que las recomendadas miden 30x12x3 o menos.

Por lo que he visto y me han contado, las baterías con dimensiones mayores a 30x12 mm2 de plano no caben en el hueco que dejan los sockets de la MCU.

El alto depende de la altura de los pines pero el máximo lo impone la ventana de la carcasa. No lo he medido por mí mismo.

También he visto instalaciones en las que la batería queda entre la PCB y la tapa trasera del teclado. En estos casos, la batería queda expuesta a los pines de los componentes soldados a la placa como son, diodos y pulsadores, que podrían perforarla, lo que causaría que se incendiase. Sin embargo, el espacio parece ser suficiente para una batería de 3 mm de alto y utilizar diodos SMD podría minimizar el riesgo de perforado, aunque pueden reducir el espacio disponible.

Las baterías se pueden poner en paralelo para aumentar la capacidad total.

Una batería de 90 mAh puede durar unas 2 semanas sin necesidad de carga.

También es posible utilizar baterías de móvil.

**Comment by jisbert** [comment]
He preguntado. También he preguntado como montar la batería para que se quede quieta en su sitio.

Tom solo me ha respondido que la 301535 me valdría, así que me imagino que lo más importante es el alto.

Además, luego he mencionado a otro chico porque él ha instalado una batería de móvil en su teclado, una batería que es mucho más grande aunque, al parecer, igual de alta. El no la ha puesto debajo de las n!n, si no que lo ha hecho a un lado. Sin embargo, eso hace que esté más expuesta a los pinchos de los puntos de soldadura, lo que le preocupaba y por eso iba a aumentar la separación con la tapa trasera.

En principio yo no debería tener ese problema porque voy a usar diodos SMD. Aunque, claro, están los pinchos de los switches. Así que mejor me quedo con la 301535.

**Comment by jisbert** [comment]
Me he decidido a medir el hueco antes de comprar nada. Tampoco sé cómo hace esta gente para que la batería se quede en su sitio.

**Comment by jisbert** [comment]
Este artículo sobre baterías es el que más información me ha proporcionado.

https://github.com/joric/nrfmicro/wiki/Batteries

**Comment by jisbert** [comment]
He decidido comprar las 301225/301030 de España y las 301230 de China, si veo que me quedo corto con estas.

**Comment by jisbert** [comment]
Una de comprar varias baterías es que se pueden usar en paralelo.

**Comment by lejouson** [comment]
He comprado [5 302030 de 110 mAh](https://es.aliexpress.com/item/4000336507750.html?spm=a2g0s.9042311.0.0.17cb63c0bjn8Oi) de Aliexpress.

**Comment by lejouson** [comment]
He recibido un SMS indicando que tendré que realizar trámites aduaneros.

La [normativa para importaciones cambió el 1 de junio](https://www.agenciatributaria.es/AEAT.internet/Inicio/La_Agencia_Tributaria/Campanas/IVA_y_comercio_electronico/_INFORMACION/Informacion_general/Nuevas_reglas/_A_quienes_afectan_/Vendedores/_Cuales_son_los_cambios_a_partir_del_1_de_julio_de_2021_/_Cuales_son_los_cambios_a_partir_del_1_de_julio_de_2021_.shtml) y ahora todos los artículos, incluidos los que tengan un valor inferior a 22 € tienen que tributar IVA. A pesar de que el vendedor haya incluido IVA en la factura, no tiene validez si no está dado de alta en la ventanilla única de importación (IOSS).

El coste del IVA no es elevado en este caso, unos 1,70 €. Sin embargo, Correos (más concretamente la empresa del grupo, ADTPostales), cobra un importe por realizar la gestión que puede ascender a más de 20 €. A pesar de todo, en muchos de los casos, cuando el importe es tan bajo, el paquete no es retenido en aduanas. El SMS se envía automáticamente cuando el envío se registra en Correos, aunque ello no implica que el paquete vaya a ser retenido.

[Este artículo](https://www.adslzone.net/reportajes/e-commerce/evitar-pagar-aduanas-adtpostales/) de ADSL zone explica cómo hacer el trámite telemáticamente para evitar el cargo por el servicio.

[Este grupo de facebook](https://www.facebook.com/groups/620094814762441/) resuelve consultas sobre este tema.

El código para importar baterías de litio de estas características es el [8507600090](https://ec.europa.eu/taxation_customs/dds2/taric/taric_consultation.jsp?Lang=es&Taric=8507600090&Expand=true&SimDate=20190924#8507600090). No existe ninguna limitación para importar este tipo de baterías y puede haber cualquier número de ellas en el paquete. Más información sobre importar baterías de ión-litio en [este artículo](https://www.intercoex.com/es/blog/importacion-baterias-ion-litio-sus-impuestos).
